replicaCount: 2

image:
  repository: 475309741409.dkr.ecr.ap-southeast-2.amazonaws.com/gitops-demo
  tag: "7"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb

  host: ""

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
