apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-demo

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: gitops-demo

  template:
    metadata:
      labels:
        app: gitops-demo

    spec:
      containers:
        - name: gitops-demo

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}

            initialDelaySeconds: 30
            periodSeconds: 10
